### ISSUE TITLE
Video recording on Android kills Appium node instance

### ISSUE THREAD

**Issue by sskorol** [isonic1/flick#17]
Hi @isonic1 

Just tried flick video recording feature on real devices. 

It works good in the following cases:
 - video recording via cmd on both ios / android platforms;
 - video recording via selenium grid hub with appium node on ios device;

It doesn't work unexpectedly on real android device via selenium grid hub / appium node. When recording is started, it just kills appium node cmd window.

Surprisingly there's nothing special in hub / node logs. Node just stops working.

```
platform: "ANDROID",
version: "5.1.1",
manufacturer: "samsung",
model: "SM-J200G",
sdk: "22",
host OS: Mac OS X 10.11.6,
appium: 1.6.0
```

Any idea about the root cause?

**Comment by isonic1** [comment]
Yeah, I just recently ran into this issue too. It's fixed now. Do a ```gem update flick``` to get the fixed version. Thanks for reporting!

**Comment by sskorol** [comment]
@isonic1 thanks for the fix! However I can't get a new version. 
`gem update flick` gives:
`Nothing to update` output.

**Comment by sskorol** [comment]
I can confirm that it works fine now. However, still missing on rubygems.

**Comment by isonic1** [comment]
@sskorol yeah, some reason the push to rubygems.org timed out and the gem wasn't published. The latest gem 0.3.5 should be there now. Thanks again for reporting this!
