### ISSUE TITLE
[v0.2.1][video][android] Flick can't record video from device.

### ISSUE THREAD

**Issue by alter-al** [isonic1/flick#6]
After updating flick to v0.2.1 I couldn't record video from my Android.

**Environment:**
Android 4.4.2

**Steps:**
1. Connect device to computer (uidd displayed in adb devices)
2. code in bash: "flick video -a start -p android"

**Result:**
Message in my bash: "Device is NOT Recordable!!!"

**Comment by isonic1** [comment]
Yea, I'll fix it. You can use the older version until it's fixed. Do a "gem uninstall flick" and choose 0.2.1. or if that is your only version do "gem install flick -v 0.2.0". Thanks for reporting.

**Comment by isonic1** [comment]
@alter-al this is fixed now. You can do a "gem update flick" to get the fix. Thank you for reporting it!

**Comment by alter-al** [comment]
bug wasn't fixed for me on flick 0.2.2.
"Device is NOT Recordable!!!"

**Comment by isonic1** [comment]
@alter-al ok, sorry about that. There was a invalid print statement incorrectly displaying that. You should still have been able to record on the device, though. I've removed that statement and uploaded a new version of flick. Thank again for reporting and sorry for the confusion.

**Comment by alter-al** [comment]
@isonic1, in v0.2.3, when I try "flick video -a start -p android" - nothing happens. No error messages, but recorder also not started.

**Comment by isonic1** [comment]
hmm, if you do a "ps -aux | grep flick" from terminal you do not see a
process running?

**Comment by isonic1** [comment]
@alter-al I removed the print statements during the recorder so you shouldn't see anything after it's started. You should see a process running for flick, though. If you do a "flick video -a stop -p android" you should hopefully then see a video in the directory you ran from.

**Comment by alter-al** [comment]
```
pc-5-167:Desktop aap$ flick video -a start -p android
pc-5-167:Desktop aap$ ps -ax | grep flick
 6891 ??         0:00.01 adb -s 32004f0970619000 shell screenrecord --time-limit 180 --size 720x1280 sdcard/flick/video-single.mp4
 6927 ttys000    0:00.00 grep flick
pc-5-167:Desktop aap$ flick video -a stop -p android -n save --trace

Stopping Recorder!!!
[Importer] Unknown input file type for "/Users/aap/.flick/32004f0970619000/video-single.mp4"
Error appending /Users/aap/.flick/32004f0970619000/video-single.mp4: End Of Stream / File
Saving to /Users/aap/Desktop/save.mp4
/Users/aap/.rvm/gems/ruby-2.3.0/gems/flick-0.2.3/lib/flick/video.rb:101:in `rename': No such file or directory @ rb_file_s_rename - (/Users/aap/.flick/32004f0970619000/save.mp4, /Users/aap/Desktop/save.mp4) (Errno::ENOENT)
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/flick-0.2.3/lib/flick/video.rb:101:in `stop_record'
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/flick-0.2.3/lib/flick/video.rb:46:in `stop'
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/flick-0.2.3/lib/flick/video.rb:25:in `run'
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/flick-0.2.3/bin/flick:32:in `block (2 levels) in <top (required)>'
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/aap/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by isonic1** [comment]
Ok. I'm not sure the issue is. I'm without an android phone at the moment
but I have one being shipped to me now. Once I get the device I can test
this out and fix the issue. Sorry for the troubles. Go ahead and use the
older version of flick before this issue occurred. Thank you again for
reporting this.

**Comment by isonic1** [comment]
@alter-al this is fixed now. sorry for the delay as it took forever for the android phone to come in the mail.
